# Site
name: "UoNMHC"
title: "University of Nottingham Men's Hockey"
description: "Welcome to the University of Nottingham Men's Hockey Club "
logo: 'assets/images/ClubCrestBlack.png'
newsletterlogo: 'assets/images/SmallUoNSportLogo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
url: https://uonhockey.club
google_analytics: 'UA-xxxxxxxx-1'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: uon


# Authors
authors:
  UoNHockey:
    name: UoN Men's Hockey Club
    display_name: UoNMHC
    email: uonmhc@gmail.com
    web: https://uonhockey.club
    twitter: https://twitter.com/uon_hc
    description: "Posts from the committee of UoNMHC"
    avatar: 'assets/images/ClubCrestBlack.jpg'
  gil:
    name: Alex Gillespie
    display_name: Alex 
    avatar: 'assets/images/GilAvatar.jpg'   
    email: ldyag8@nottingham.ac.uk
    description: "Posts from the Social Media Secretary of UoNMHC"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
